project:
  #output-dir: ../../docs/slideshows
  #output-dir: slides
  render:
    - "*.qmd"
    - "!tables/"
  post-render: 
    - share_libs.py
csl: csl/inline-gpt.csl
bibliography: cs.bib
execute:
  freeze: auto
format:
  revealjs:
    margin: 0.1 # defaults to 0.1. Set to 0 for more space
    embed-resources: false # creates a massive html file
    standalone: false
    controls: false
    center: false # if ture, annoyingly centres text vertically. Always false :)
    menu: true
    multiplex: false # link to web page so people can follow on phone!
    slide-number: true
    show-slide-number: print
    progress: true
    chalkboard: false
    auto-animate-easing: ease-in-out
    auto-animate-unmatched: true
    auto-animate-duration: 1
    auto-play-media: true
    email-obfuscation: javascript
    #logo: ../sourcefiles/logos/genomicc_logo_white.png
    # THEMES
    theme: default
    #theme: beige
    #theme: blood
    #theme: dark
    #theme: league
    #theme: moon
    #theme: night
    #theme: serif
    #theme: simple
    #theme: sky
    #theme: solarized
    css: "_includes/css/people_gallery.css"


# SHORTCUTS

# M - show menu
# F - fullscreen
# O - overview
# S - speaker view
# E - print view
# N, rightarrow, space - next slide
# P, leftarrow - next slide
# esc - exit fullscreen
# alt-rightarrow - navigate without fragments
# alt-leftarrow - navigate without fragments
# SHIFT-rightarrow - jump to end
# SHIFT-leftarrow - jump to beginning
# Alt - zoom on click

# Notes canvas and chalkboard SHORTCUTS

# C - Toggle notes canvas 
# B - Toggle chalkboard 
# E - Reset all drawings  BACKSPAC
# L - Clear drawings on slide DE
# X - Cycle colors forward  
# Y - Cycle colors backward 
# D - Download drawings 

# Custom SHORTCUTS

# G - 
# H -
# J -
# K -









